[package]
name = "testcrate"
version = "0.1.0"
authors = ["Yoav Koplon <yoavkoplon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
yara-src = { path = ".." }
